name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      uses: heroku/rust-cargo-musl-action@v1
      with:
        command: 'build'
        flags: '-r --features vendored-openssl'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bot
        path: ${{ steps.compile.outputs.release-dir }}/bot
